unplugin/unplugin-auto-import

examples/nuxt/nuxt.config.js
src/presets/index.ts
src/presets/nuxt-composition-api.ts

Updates preset name from `@nuxt/composition-api` to `@nuxtjs/composition-api` as it generates incorrect imports

fix: nuxt composition api preset name

---

README.md

As I understand this plugin works at the build stage and may be installed with the `-D` flag.

Install as a dev dependency

---

src/presets/vue.ts

`defineAsyncComponent` is available in `@vue/composition-api`: https://github.com/vuejs/composition-api/pull/644
Needed for https://github.com/antfu/unplugin-vue2-script-setup/issues/43 to work with `unplugin-auto-import`

feat: add defineAsyncComponent to the composition api methods

---

src/presets/vue.ts
test/__snapshots__/dts.test.ts.snap

`triggerRef` is supported by composition-api: https://github.com/vuejs/composition-api/blob/07cad7236ad1201f409541c5073c8d4fd19c900e/src/reactivity/index.ts#L18

 feat: add triggerRef to the composition api methods 

---

README.md

I came across the same problem found in #90 when using a Vite starter template, since `tsconfig.json` is set to only include **'src/'** and the `auto-imports.d.ts` is generated at **project root** by default.
So we could mention this in README for people like me. Better than none, right?

doc: typescript setup

---

src/presets/preact.ts

According to an official [Preact](https://preactjs.com/guide/v10/hooks) document about importing hooks APIs, it should be imported from `preact/hooks`, not from `preact`.

fix: preact hook apis should be imported from 'preact/hooks'

---

package.json

https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing
close #240

fix: add missing `types` fields in `exports`

---

.gitignore
examples/vite-react/src/App.tsx
examples/vite-react/vite.config.ts
src/core/ctx.ts
src/types.ts

~~Add support for React Component as an option.~~
**Updated:**
- Support tsx, jsx by default
- Add option `defaultExportByFilename`:  boolean
- When `true`, use file name as default export's alias
#268
No.

feat: support tsx, jsx by default and add option `defaultExportByFilename`

---

package.json
pnpm-lock.yaml
src/nuxt.ts

This PR make `unplugin-auto-import` compaible with the new `nuxt@3.0.0` release, this is needed until Nuxt supports using resolvers from this plugin, in order to use e.g. `ElementPlusResolver` in Nuxt projects.
https://github.com/nuxt/nuxt.js/issues/11785

feat: support nuxt@3.0.0

---

package.json
pnpm-lock.yaml

Removes hard dependency on @nuxt/kit, changing it to an optional peer dependency so that non-nuxt projects aren't forced to take on 100 additional dependencies in order to use this package.
Fixes #334

fix: remove hard dependency on nuxt, close #334 

---

src/core/ctx.ts

1. when code does not need auto inject api and relevant cache should be removed.
2. imporove cache performance and resolve mistake cause by race condition.

fix(cache): imporove cache performance and resolve cache mistake

---

src/core/ctx.ts
src/types.ts

add new option about **unimport**. 
> 💡Inject the imports at the end of other imports
The default value is **true** for the current version, which has no effect on upgrades.
no.
My config is 
```ts
AutoImport({
imports: [
'vue',
'vue/macros',
'vue-router',
'vue-i18n',
'@vueuse/core',
'pinia',
{
vue: ['createVNode'],
'@/i18n/use-locale': ['dayjs'],
'@/utils/use-search': [['default', 'useSearch']],
'@/utils/emitter': [['default', 'emitter']],
'@/utils/page-tab-util': [
'finishPageTab',
'removePageTab',
'setPageTab'
],
'@/store/modules/theme': ['useThemeStore'],
'@/store/modules/dict': ['useDictStore'],
'@/store/modules/user': ['useUserStore'],
'ant-design-vue': ['message', 'Modal'],
'@ant-design/icons-vue': ['ExclamationCircleOutlined'],
'ant-design-vue/es/form': ['useForm'], …
```

feat(injectAtEnd): add new option

---

src/core/ctx.ts

Hi,
First of all, I wanted to thank you for creating and maintaining `unplugin-auto-import`. I recently started using it in my project after it was recommended by Posva, and I have found it to be very helpful.
However, I ran into a tiny issue with the warning message that is displayed when no imports are defined. After investigating the issue, I realized that the warning message is not necessary in all cases, especially when the "dirs" option is specified.
To fix this issue, I modified the source code to check for the "dirs" option and skip the warning message if it is specified. Here is an example of how I use this package in my project:
```ts
require('unplugin-auto-import/webpack')({
dirs: [path.resolve(__dirname, '../../app/javascript/stores')],
dts: path.resolve(__dirname, …
```

fix: avoid warning when not needed, fix #314

---

src/core/unplugin.ts

[minimatch](https://github.com/isaacs/minimatch#windows) must require `/`, even for `glob`，dir glob will not be slashed when it is resolved in windows, so I mentioned this pr。This enables directories to be rescanned when hmr on windows

fix: slash dir glob to support windows match

---

README.md
package.json
src/rspack.ts

This PR adds an `rspack` export to the package, using unplugin's experimental [rspack](https://www.rspack.dev/) support.
This has not been brought up yet.
rspack just recently [added support](https://github.com/web-infra-dev/rspack/issues/2350) for vue-loader. As far as I have tested it, this works flawlessly. Having Vue support in rspack was a good occasion to look for rspack support in some popular build tools that commonly come with Vue projects.

feat: support rspack

---

src/core/ctx.ts
test/dts.increase.test.ts
test/tmp/dts.increase.d.ts

when file name like:  {id} or {  id     }, dts reg match error
fix #394

fix: improve dts parsing regex

---

src/core/eslintrc.ts

`eslintrc.globalsPropValue` has already been normalized at
https://github.com/antfu/unplugin-auto-import/blob/c2a948fed90feceb100aedfbc3050e7947e1c28d/src/core/ctx.ts#L46
and current implementation does not support documented `false` value

fix: support `eslintrc.globalsPropValue: false` correctly

---

README.md

This PR includes the breaking changes introduced in `v0.17.0` about CJS default exports:
- webpack
- rspack (no idea if will resolve default export `export.__esModule=true`, I need to do a test)
- esbuild (no idea if will resolve default export `export.__esModule=true`, I need to do a test)
- Vue CLI
- quasar: updated also Vite usage
closes #452

docs: update cjs usage in readme file

---

examples/vite-astro/astro.config.mjs
examples/vite-astro/src/components/Card.astro
examples/vite-astro/src/components/Card.svelte
examples/vite-astro/src/components/Card.vue
examples/vite-astro/src/utils/contants.ts
src/core/ctx.ts
src/types.ts

Check title.
closes #352 
This PR also removes `vue/macros` in `vite-astro` example since `Vue 3.4` has removed it

feat(astro): add `.astro` files to default include

---

README.md
src/core/ctx.ts
src/core/eslintrc.ts

If eslintrc filepath is a.js suffix, default export is provided
解决.json不支持最新版本的eslint8.57.0的使用
#487

feat(eslint): support generate mjs/cjs eslint config #488

---

src/core/ctx.ts

Focusing on the same bug in #498 . 
If `eslintrc.filepath` ends with "js", it will generate a javascript file (which is add in #494 ), however the `parseESlint` function still treat it as JSON file, which triggers an error.
In this PR, `parseESlint` returns `{}` if filepath ends with "js", instead of the `String.replace()` method used in #498 . Parsing is skipped in non-json mode.
If I understand correctly, skipping the parsing of previously generated eslint files would only have an impact on artifacts when the generated file was manually modified or the scope of automatic imports is narrowed. I'm not sure if resolve work fine, since I haven't use them.
null
Maybe it will be better to be able to "import" it, but I cannot find an elegant way to do that.

fix: skip `parseESlint` if eslint filepath is a js file

---

README.md
src/core/biomelintrc.ts
src/core/ctx.ts
src/types.ts

Hi, Thank you for this plugin. awesome work.
I’ve added support for the BiomeJS linter.
The user can choose to enable either Eslintrc, Biomelintrc or both which is very handy.
and I’ve also updated the readme documentation accordingly.
```js
biomelintrc: {
enabled: true, // Default `false`
filepath: './.biomelintrc-auto-import.json', // Default `./.eslintrc-auto-import.json`
},
```

feat: add support for BiomeJS config

---

src/core/unplugin.ts

alias start With `@` may be resolved as installed deps
fix: #514

fix: should only filter installed packages for optimization

---

README.md
src/core/ctx.ts
src/types.ts

When using vue-loader experimentalInlineMatchResource, the request will have an additional .js/.ts extension to match the js/ts module rule
```diff
// without experimentalInlineMatchResource
- src/App.vue?vue&type=script&setup=true&lang=ts
// with experimentalInlineMatchResource
+ src/App.vue.ts?vue&type=script&setup=true&lang=ts
```
But the default include RegExps failed to match the request

fix: compatible with vue-loader experimentalInlineMatchResource

---

src/core/unplugin.ts

This PR fixes the Vite HMR path matching issue by converting absolute file paths to project-relative paths before comparing with glob patterns.
Before:
After: 
fix #551, fix #553

fix: resolve path matching in hmr by using relative paths

---

src/core/ctx.ts
src/core/unplugin.ts

Implements the [hook filters](https://unplugin.unjs.io/guide/#filters) to improve perf with Rolldown/`rolldown-vite`
https://github.com/e18e/ecosystem-issues/issues/171

perf: add hook filters

---

README.md
src/types.ts
test/search.test.ts

This PR uses `ScanDirExportsOptions` from `unimport`, and removes the local definition.

feat: use `ScanDirExportsOptions` from unimport

---

package.json
pnpm-lock.yaml

`unplugin-auto-import` causes a peer dep warning in my project. This PR aims to fix it
```
 WARN  Issues with peer dependencies found
└─┬ @nuxt/ui 3.3.0
└─┬ unplugin-auto-import 19.3.0
└── ✕ unmet peer @nuxt/kit@^3.2.2: found 4.0.2
```

chore: update `@nuxt/kit` to v4

---

src/core/ctx.ts
src/core/unplugin.ts

This PR fixes hot reload functionality when `dirs` is configured without wildcards.
Previously, hot reload only worked for patterns like `./composables/*` or `./composables/**` but failed for `./composables`:
```js
// ✅ Works (with wildcards)
dirs: ['./composables/*', './composables/**']
// ❌ Broken (without wildcards) 
dirs: ['./composables']
```
The issue was that `picomatch` couldn't properly match files against directory paths without glob patterns.
The fix normalizes directory paths using `unimport's normalizeScanDirs` to properly handle both wildcard and non-wildcard patterns, ensuring files are correctly matched regardless of configuration style.
As an additional optimization, it now skips hot reload checks for auto-generated config files to prevent unnecessary re-scans.
resolved …

fix: dirs hot reload without wildcards
