unplugin/unplugin-auto-import

README.md
I think the examples at the top got mixed up.
Thanks for another great tool <3
=> docs: fix examples

test/__snapshots__/dts.test.ts.snap
Sorry for test issues with #34. I just used GitHub file edit and didn't check tests
=> chore: fix tests

README.md
=> docs: update include mappings

package.json, playground/App.vue, playground/package.json, playground/vite.config.ts, pnpm-lock.yaml, src/presets/vueuse-core.ts
=> feat: use `local-pkg` to avoid using `__dirname` on `esm` env

src/presets/vue.ts
=> feat(preset): Added `resolveComponent` to vue

src/core/transform.ts
Fix #97 
Unfortunately I can't reproduce this bug on tests or fresh Vue project.
=> fix: dollar sign edge case

src/core/transform.ts, test/__snapshots__/transform.test.ts.snap, test/fixtures/custom.js, test/transform.test.ts
Support 
```ts
AutoImport({
imports: {
jquery: [
['default', '$'],
['default', 'jQuery'],
],
},
}),
```
=> feat: import multiple defaults

examples/vite-react/package.json, examples/vite-react/src/App.tsx, examples/vite-react/src/layouts/MainLayout.tsx, examples/vite-react/src/main.tsx, examples/vite-react/src/views/PageA.tsx, examples/vite-react/src/views/PageB.tsx, examples/vite-react/vite.config.ts, pnpm-lock.yaml, src/presets/index.ts, src/presets/react-router-dom.ts, src/presets/react-router.ts
add `react-router` & `react-router-dom` preset, compatible with v6👾
=> feat(preset): add `react-router` & `react-router-dom`

src/index.ts
fixed https://github.com/antfu/unplugin-auto-import/issues/111
=> fix(webpack): config generation

src/presets/index.ts, src/presets/uni-app.ts
#102 
- The package is wellknown and well-documented, and satisfied with one of the following conditions:
=> feat(preset): add uni-app

esbuild.d.ts, index.d.ts, nuxt.d.ts, package.json, rollup.d.ts, types.d.ts, vite.d.ts, webpack.d.ts
using `typesVersions` field in package.json to redirect typings
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions
=> feat: typings folder redirects

src/presets/vue-marcos.ts
=> feat(preset): add vue/macros

examples/vite-react/package.json, examples/vite-react/src/App.tsx, examples/vite-react/src/i18n.ts, examples/vite-react/src/react-i18next.d.ts, examples/vite-react/vite.config.ts, pnpm-lock.yaml, src/presets/index.ts, src/presets/react-i18next.ts
Translation hook for https://react.i18next.com/.
=> feat(preset): react-i18next

src/core/ctx.ts, test/dts.test.ts
windows path like this E:/test/unplugin-auto-import/playground/composables/foo.ts
=> fix: windows path

src/core/resolvers.ts
=> fix: HMR reload (resolver side-effects)

package.json, scripts/postbuild.ts
Address https://github.com/microsoft/TypeScript/issues/50067 but in a simpler way
N/A
N/A
=> feat: use `type=module`

src/presets/index.ts, src/presets/recoil.ts
=> feat: add recoil preset

src/presets/vue-router.ts
add presets
```ts    
'useLink',
'onBeforeRouteLeave',
'onBeforeRouteUpdate'
```
=> feat: update vue-router preset

src/presets/vue-router.ts, src/presets/vue.ts
add `resolveDirective` api. Do you need 'with*' apis ?
e.g.  `withDirectives` ,`withModifiers`
[https://vuejs.org/api/render-function.html#withdirectives](https://vuejs.org/api/render-function.html#withdirectives)
=> feat: add vue `resolveDirective` to preset

src/presets/index.ts, src/presets/vue-router-composables.ts
添加 vue-router@3 版本的组合式 api 方法
https://github.com/vuejs/vue-router/tree/dev/src/composables
https://github.com/vuejs/vue-router/pull/3769
=> feat: add vue-router/composables preset

src/core/ctx.ts
fix: https://github.com/antfu/unplugin-auto-import/issues/173#issuecomment-1134139332
=> fix: generator config (no such file or directory)

playground/vite.config.ts, src/core/ctx.ts, src/core/unplugin.ts, src/types.ts
cache dynamic imports for generate dts,eslint
https://github.com/antfu/unplugin-auto-import/issues/233
=> feat(cache): cache dynamic imports for generate dts,eslint

README.md
=> docs: add import type example

src/core/ctx.ts, src/types.ts
resolve problem of debug point.
https://github.com/antfu/unplugin-auto-import/issues/382
https://github.com/antfu/unplugin-auto-import/issues/194
=> fix: generate sourcemap with hires (#382)

package.json, pnpm-lock.yaml
bump dependencies & fix audit @antfu/utils 0.7.2 ( security prototype pollution )
Tested on local environment , everything works well after the update.
=> cho:Re bump dependencies & fix audit @antfu/utils 0.7.2

playground/vite.config.ts
Remove cache option from AutoImport configuration.
See https://github.com/antfu/unplugin-auto-import/commit/551e7c77824cad92b57209cea6ad5c2d65a7b1f3
Remove removed cache option of config.
=> docs: remove depercated options

README.md
Update readme footer copyright: include `-PRESENT` suffix to the year
NA
=> docs: update readme copyright

examples/solid-js/package.json, examples/solid-js/vite.config.ts, examples/vite-react/package.json, examples/vite-svelte/package.json, package.json, pnpm-lock.yaml
Any example NOT working:
- vite-svelte: added type module
- vite-react: added type module
- solid-js: added type module, switched to `@solid/router`  from `solid-app-router`
- included `@svgr/plugin-jsx` as dev dependency in root to run `vite-react` example
=> chore: fix examples

examples/solid-js/package.json, examples/solid-js/vite.config.ts, examples/vite-astro/package.json
This PR includes:
- cleanup some missing/deprecated entries in solid example and change package name
- change package name in astro example
=> chore: cleanup examples

src/esbuild.ts, src/rollup.ts, src/rspack.ts, src/vite.ts, src/webpack.ts
-----
<a href="https://stackblitz.com/~/github.com/iiio2/unplugin-auto-import/tree/iiio2/chore/fix-grammar"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/iiio2/unplugin-auto-import/tree/iiio2/chore/fix-grammar)._
=> chore: fix grammar

README.md
=> docs: fix tiny typo

src/esbuild.ts, src/rollup.ts, src/rspack.ts, src/vite.ts, src/webpack.ts
The upstream typing issue has been fixed
related #109
=> fix: types fixed by upstream

README.md, package.json, pnpm-lock.yaml, src/rolldown.ts
Support [`rolldown`](https://github.com/rolldown/rolldown) export to use this plugin with [`tsdown`](https://github.com/rolldown/tsdown), [`rolldown`](https://github.com/rolldown/rolldown) or [`rolldown-vite`](https://github.com/vitejs/rolldown-vite)
Resolves: #585
I'm not sure if `rolldown` should be added as a dev dependency. Could I request some feedback on this?
=> feat: add support for `rolldown`
